### ISSUE TITLE
Can't reload server cache

### ISSUE THREAD

**Issue by Pab89** [vmitchell85/alforge#10]
Hi
Thanks for a great plugin, I have been using it for years it really helps me in my day-to-day! 

Suddenly I can not update the server cache anymore, everything else works as always. But I have no way of adding new server or sites and get them in the Alfred results. I have tried to debug it myself, but can not figure out how to solve it.

I check the Alfred log, which returned the following (when running "Reload Server & Site Cache":

[13:51:04.833] AlForge[Keyword] Processing complete
[13:51:04.834] AlForge[Keyword] Passing output '' to Run Script
[13:51:40.575] STDERR: AlForge[Run Script] 35:44: syntax error: Der må ikke følge “"” efter id. (-2740)
[13:51:40.583] AlForge[Run Script] Processing complete
[13:51:40.584] AlForge[Run Script] Passing output '' to Post Notification

FYI the "Der må ikke følge “"” efter id" is danish, and is translated to "There can follow a """ after an id"

I hope you can help me out, as I would love to continue using the plugin

**Comment by vmitchell85** [comment]
@Pab89 I'm sorry to hear you're having issues. I just reloaded my cache with no errors.

There should be a file with all your server and site data in `~/.alforge/data.json` can you open that file in an editor and see if it's valid JSON?

**PLEASE DO NOT POST THAT FILE HERE, IT HAS SENSITIVE DATA ABOUT YOUR SERVERS**

Report back and I'll continue trying to help.

**Comment by Pab89** [comment]
Hi, thanks for the fast reply.

Was away on vacation just came back. There is no ~/.alforge/data.json.
Can it be stored somewhere else?

FYI I still have my old sites in cache, but I can not get my new sites in. I have around 100 servers/sites

**Comment by Pab89** [comment]
Did a "find / -name data.json" and found it in ~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.vmitchell85.alForge :) And it is valid json

**Comment by vmitchell85** [comment]
Okay, I think I moved the file into the caches a while back, so it makes sense that it's there.

I figured it would have to be a invalid JSON issue. Can you move that `data.json` file out and try to reload again?

**Comment by Pab89** [comment]
That did the trick! Thanks, and thanks for replying so fast

**Comment by Pab89** [comment]
FYI, one suggestion would be to make the "forge open" and "forge term" case insensitive. :) Just an idea.

**Comment by vmitchell85** [comment]
@Pab89 Can you create a new issue for that, and I'll try to get it fixed.

**Comment by Pab89** [comment]
Will do
