### ISSUE TITLE
Can not open servers anymore, only sites

### ISSUE THREAD

**Issue by Pab89** [vmitchell85/alforge#14]
Hi there

First of all thanks for a great workflow.

One small problem has arised after installing it on a new computer.
Whenever i try to open a server, i just get a error message.
Opening af site works fine.

I have attached a screenshot of what is happening when i try to open af server
<img width="272" alt="Skærmbillede 2021-12-03 kl  16 13 32" src="https://user-images.githubusercontent.com/2759517/144626057-68f5459d-897b-4156-a93b-9fb6058aa01b.png">

Any idea how i can fix this?

**Comment by Pab89** [comment]
For info the full text of the message is:

Der er ikke angivet nogen app til at åbne URL'en Warning:%20Undefined%20array%20key%201%20in%20/Users/philipbrechmann/Library/Application%20Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.[key goes here]/alforge/Open.php%20on%20line%2016%0A%7B%22alfredworkflow%22:%7B%22arg%22:%22https:%5C/%5C/forge.laravel.com%5C/servers%5C/516201%22,%22variables%22:%7B%22push_title%22:%22AlForge%20Notification%22%7D%7D%7D

"Der er ikke angivet nogen app til at åbne URL'en"  means in english "There is no app to open the url"

**Comment by vmitchell85** [comment]
@Pab89 try this pre-release and let me know if it works for you after: https://github.com/vmitchell85/alforge/releases/tag/1.4.3RC

**Comment by Pab89** [comment]
That worked! Thanks for the ultra fast reply
Is there anywhere i can donate to you?

**Comment by vmitchell85** [comment]
@Pab89 I haven't set up GitHub sponsors yet, but you can "buy me a coffee" here: https://www.buymeacoffee.com/kgn867ldz

But in full transparency, @aglipanci is the one who fixed your issue in #13!

**Comment by Pab89** [comment]
Thanks, just did. :)
