### ISSUE TITLE
Feature Request: Fetch server IP

### ISSUE THREAD

**Issue by syropian** [vmitchell85/alforge#2]
Sometimes I want to quickly grab the IP of one of my servers. Would be great to be able to get it on the pasteboard via Alfred. Thanks for the workflow, looking forward to trying it out! 🙏

**Comment by vmitchell85** [comment]
Great idea! I'll work on implementing it...

**Comment by vmitchell85** [comment]
Just added this, will be tagging a new release soon and uploading to Packal
