### ISSUE TITLE
Stopped loading my servers :(

### ISSUE THREAD

**Issue by syropian** [vmitchell85/alforge#3]
Went to use this today and it wasn't showing any servers. Set a new API key and got `Loaded 0 servers into cache!` Tried resetting all my Alforge data, but same problem.

**Comment by vmitchell85** [comment]
So you had been using a previous version, updated to the latest, and it stopped working?

**Comment by vmitchell85** [comment]
Just replicated the issue on my machine... I'll push a fix soon

**Comment by vmitchell85** [comment]
Just pushed a fix... let me know if it works for you and I'll close the issue.

Sorry about that...

**Comment by syropian** [comment]
No problem, seems to be working great now, thanks!
