### ISSUE TITLE
Trouble updating to latest version

### ISSUE THREAD

**Issue by alexpgates** [vmitchell85/alforge#4]
I was consistently hitting the split() error (that you've recently fixed), even after completely removing my existing alforge workflow and installing the workflow from the github source. I also cleared the Alfred cache. 
Eventually I just replaced Deploy.php directly in the Alfred.alfredpreferences (after 'show package contents') to fix the deploy routine, but I know there are other scripts with outdated code.

Any idea why installing the new workflow didn't install the latest code? Is there another cache to clear somewhere? I am using Dropbox to sync my preferences.

**Comment by vmitchell85** [comment]
The `split()` error hasn't been put out into a tagged release yet... which also means the .workflow file hasn't been updated either.

 I'll see if I can do that today.

**Comment by alexpgates** [comment]
Ah! That makes sense. 

No worries at all, and certainly no rush. 

Unrelated, if you have any feature requests or want some help along the way, Hacktober is a great time to put those out. I'd certainly love to contribute. I may play around with some other parts of the Forge API that aren't supported yet, unless you have specific direction where you'd like to go. 
Thanks!

**Comment by vmitchell85** [comment]
I've tagged and released a new version... great idea on Hacktoberfest... will add some issues.
